function [scenario, egoVehicle, ] = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.13 (R2022b) and AutoroadCenters = [0 0 0;mated Driving Toolbox 3.6 (R2022b).
% Generated on: 13-Mar-2023 17:20:45

% Construct a drivingScenario object.
scenario = drivingScenario('SampleTime',0.1, 'StopTime', 20);

% Add all road segments
roadCenters = [0 0 0;
    120 0 0];
laneSpecification = lanespec([2,2]);
road(scenario, roadCenters, 'Name', 'Road', 'Lanes', laneSpecification);

roadCenters = [0 20 0;
    120 20 0];
laneSpecification = lanespec([2,2]);
road(scenario, roadCenters, 'Name', 'Road', 'Lanes', laneSpecification);

roadCenters = [0 40 0;
    120 40 0];
laneSpecification = lanespec([2,2]);
road(scenario, roadCenters, 'Name', 'Road', 'Lanes', laneSpecification);


roadCenters = [-40 0 0;
    -40 80 0];
laneSpecification = lanespec([1,1]);
road(scenario, roadCenters, 'Name', 'Road', 'Lanes', laneSpecification);

roadCenters = [0 0 0;
    0 80 0];
laneSpecification = lanespec([1,1]);
road(scenario, roadCenters, 'Name', 'Road', 'Lanes', laneSpecification);

roadCenters = [40 0 0;
    40 80 0];
laneSpecification = lanespec([1,1]);
road(scenario, roadCenters, 'Name', 'Road', 'Lanes', laneSpecification);

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-60 20 0], ...
    'Name', 'Car');
% waypoints = [-40 21.4; -20 21.4; 0 21.4; 20 21.4; 40 21.4];
% speed = [2 2 2 2 2];
% smoothTrajectory(egoVehicle, waypoints, speed);

actorVehicle = vehicle(scenario, ...
    'ClassID', 2, ...
    'Position', [-50 21.4 0], ...
    'Name', 'Car');

waypoints = [-20 21.4; -10 21.4; 0 21.4; 10 21.4; 20 21.4];
speed = [2 2 2 2 2];

smoothTrajectory(actorVehicle, waypoints, speed);